name: tensorflow-env
channels:
  - nvidia  # NVIDIA channel for CUDA
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # Change to 3.10 or 3.11 if needed
  - pip
  - tensorflow=2.15
  - accelerate
  - datasets
  - gh
  - git
  - ipywidgets
  - jupyter-ai
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-nvdashboard
  - jupyterlab-lsp
  - pyarrow
  - python-dotenv
  - python-language-server
  - tensorboard
  - transformers
  - wandb
  - pip:
    - -r requirements.txt
